---
Name: socialmetadata
---
SiteTree:
  extensions:
    - SocialMetaSiteTreeExtension
SiteConfig:
  extensions:
    - SocialMetaConfigExtension
Member:
  extensions:
    - SocialMetaAuthorExtension
SocialMetaPageExtension:
  facebook_page_type:
    BlogPost: 'article'
    ArticlePage: 'article'
CMSMain:
  extra_requirements_javascript:
    - social-metadata/javascript/cms-social-meta.js
SocialMetaConfigExtension:
  multisites_enable_global_settings: false

---
Only:
  classexists: 'Multisites'
---
Site:
  extensions:
    - SocialMetaConfigExtension
    